ASA:dark and 1D ASA:vessel revamp (#152)
* Add source_dark table and dark_analyzer

* oops.

* Add DarkAnalyzer code

* added dark vessel analysis notebook

* Source_type row handled previously

* Add in Natural while we're here...

* Add aspect_ratio_factor to scoring

* incorporate ARF into analyzers

* temporary pre-commit version update

* add constants and ensure slick curve is calculated

* Revert "temporary pre-commit version update"

This reverts commit 1418af663f2f5e5748bff4f8b8165be3af702b75.

* Refactor analyzers to pull out common functions
Choose some new starting values
Change dark_compute_total_score() to multiply instead of add
Update ASA_Test_environment

* Add in Match IDs for dark vessels that somehow GFW has assigned an ID
automate source_type id
Illustrate some examples in the test_environment

* predicted length is float not text

* multiply arf on ASA:vessel instead of adding

* Refactor asa local rerun notebook

* tweak some parameters filter out more dark vessels

* Refactor asa collation notebook

* First pass calculate ARF and splines for each slick
WARNING ASA is broken by this

* Looks like I have to update analyzer at the same time

* undo mistaken gdf to geoseries conversion

* should have returned json instead of string?

* update test

* can't distinct on a json object...

* fix ASA to use new splines json

* add arf to slick_plus

* fix access pattern for the json splines

* Switch to extrema vertex inner angle

* First attempt at 1D Vessel ASA

* refine and add some examples

* remove traj truncation

* trim by a buffer distance from the slick

* Add centerline computation to orchestrator handler

* Swap splines for centerlines

* Refactor dark analyzer to accept multiple center points

* Update remaining "curve" and "spline" references to "centerline"

* Evaluation script and notebook

* Maybe fix some issues with graph code

* small changes

* Fix test

* Completely replace curves in analyzer

* revert ethan's partial work

* one last curve

* multiplication inside an np.array does not duplicate the object--it scales it

* Centerline based directional spray

* Slight InfrastructureAnalyzer refactor

* sometimes we try to access an out of bounds element... not sure where that's coming from...

* simplify some of the centerline spray code

* switch back to lists or coords instead of arrays of Points

* Fix for centerline bug

* ruff touch

* fix bug causing hallucinated interpolations (before/after AIS actually existed)

* handle solitary AIS point... poorly

* Remove 100m interp distance min

* Add sensitivity

* update constants import to c

* Ruff

* Oops

* more ruff

* Improve plotting of tracks

* TEST with Centerlines

* Put s1_time timestamp in the right place for interpolation

* Speed up build_trajectories by a factor of 4~5 (5s instead of 25 seconds)

* Fix anti-parallel bug, and stop comparing every point to every other point!

* Improve ASA:vessel plotting

* Change ASA:dark weighting to be independent of the slick's centerpoint (and instead only depend on length of centerline)

* divide by 0 bug

* Bugfix: TypeError: unsupported operand type(s) for +=: 'int' and 'tuple'

* Try updating geopandas libraries?

* WTF. Some library version bug that interprets timestamps as different dtypes on Jona's setup vs. the GCP environment

* New proximity scoring method

* oops

* Try new score weights

* Increase data draw in an attempt to reduce need for extrapolation

* Clean up import

* updated evaluation code to use centerlines

* Avoid assigning to views in pandas

* ruff

* try using the ais point closest to t=0 that is closest to the head/tail of the slick

* Analyzer now accepts trajectories as input

* Filter AIS infra and safe trajectories

* fix bug so that series of length 1 is always returned

* Clean up, add new collation scores

* Change Temporal score to depend on which end of the slick is closer to the AIS track

* path fix

* oops. Temporal score was assuming no image timestamp

* Role back ais_trajectories kwarg

* Fix a bug where the AIS was being filtered down by the first slick in a scene, but not starting with the unfiltered AIS when transitioning to the next slicks in the scene.

* New method for loading trajectories locally

* Move timestamp processing into one place

* Fix bug with centerlines not being updated between slicks

* Fix bug around
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
(depends on series vs dataframe being returned if there are 1 vs more rows with a given index

* Clean up engine after use

* Project to nearest points that are adjacent to image timestamp

* Collation notebooks and files

* update collation parameters

* complete loop shutdown (try to avoid open and unused loops)

* ruff and cp

* Increase grace_distance a little bit

* Include interpolated s1_time for geojson_fc

* Add s1_timestamp to geojson_fc

* Incrementally increase trajectories with each slick

* Accumulate built trajectories, but only score the relevant ones

* Cleanup variables

* Eliminate MPD

* clean notebook

* Update constants to use finetuned params

* remove moving pandas requirements

* Make projection robust up to 10 minutes of jagged ais mistake

* Average(parity) average(proximity) and max(temporal) of longest 80% of slicks

* Edge case

* After finding the head (slick end closest to the AIS), project the tail to the nearest point independent of time.

* neg timestamp isn't a thing

* Simplify

* Separate scene and slick buffer constants

* update sensitivity to sharpness (Is it a hard binary threshold or a soft one?)
Rethink how grace_distance is used.

* clean_segs = TRUE is eliminating true culprits

* Oops

* simplify centerlines to 10m

* Update parameters and constants

* Afford the same grace to the tail.

* Fix ARF=NAN bug (centerlines library bug)

* Toss out smallest 5% of polygons when making centerlines

* avoid divide by 0

* working extrapolation

* Filter AFTER interpolating and extrapolating (building) trajectories

* Changed ARF def to avoid small area polys

* Extrapolate using Kalman Filter for all points, then overwrite internal "known" broadcasts with linear interpolation
Frankenstein

* Switch to RTS

* power up DB

* -4 +3 detail window to reduce extrapolation window

* use vessel velocity to determine which tracks to extrapolate

* First pass bezier extrap

* Use bezier for interpolation, too.
accept all tracks that overlap, independent of detail window
reduce scored to those intersecting smaller time cube

* cover case where course is NAN gracefully

* faaaast

* faaaaaaaastttteeerrrrr

* TOO FAST

* comments and helper functions

* oops all marshmallows!

* sh*tnuggets
accidentally left out this function call

* more test scenes

* random triggers

* Increasing spread rate to capture Indonesian high-velocity currents (example S1A_IW_GRDH_1SDV_20210409T215314_20210409T215342_037379_0467B9_03F6)

* Collated Parameter Update

---------

Co-authored-by: Ethan Bevan <74314722+ancientpi3@users.noreply.github.com>